version: "3.8"

services:
  main-api:
    build:
      context: .
    container_name: ai-main
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always

  conversation-api:
    build:
      context: .
    container_name: ai-conversation
    command: uvicorn conversation_api:app --host 0.0.0.0 --port 8002
    ports:
      - "8002:8002"
    env_file:
      - .env
    restart: always
