name: CI/CD Docker EC2

on:
  push:
    branches: ["deploy"]

env:
  IMAGE_NAME: tungcbh/ai-process-optimizer

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME .

      - name: Push Docker image
        run: docker push $IMAGE_NAME

      - name: SSH and deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: IMAGE_NAME
          script: |
            cd /home/${{ secrets.EC2_USER }}/app

            cat > .env << 'EOF'
            ${{ secrets.ENV_FILE_CONTENTS }}
            EOF

            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
            docker pull $IMAGE_NAME

            docker stop ai-process-optimizer || true
            docker rm ai-process-optimizer || true  
            docker run -d --name ai-process-optimizer --env-file .env -p 8000:8000 -p 8002:8002 $IMAGE_NAME
