name: Deploy to EC2 via SSH

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  deploy:
    name: SSH Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/app

            if [ -d "ai-process-optimizer" ]; then
              cd ai-process-optimizer
              git fetch origin main
              git reset --hard origin/main
            else
              git clone git@github.com:T-R-I-N-H/ai-process-optimizer.git
              cd ai-process-optimizer
            fi

            docker compose down --remove-orphans
            docker compose up -d --build
            docker compose logs --tail=50
